services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks: 
      - nftMarketPlace

  backend:
    build:
      context: ./nftMarketBack
    container_name: nest-backend
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    networks:
      - nftMarketPlace
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://IvanUkrainets:UdeChnu@cluster0.yzjnh.mongodb.net/NFTMarketplace?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URI=http://localhost:4200

  frontend:
    build:
      context: ./nftMarketFront
    container_name: angular-frontend
    restart: always
    ports:
      - "4200:8080"
    depends_on:
      - backend
    networks:
      - nftMarketPlace
    environment:
      - ANGULAR_APP_API_URL=http://localhost:5001/api

networks:
  nftMarketPlace:
    driver: bridge
