export interface User {
  user_id: string,
  name: string,
  ava: string,
  email: string,
  password: string,
  wallet: string,
  volume: number,
  sold_allTime: number,
  sold_month: number,
  sold_week: number,
  sold_today: number,
  followers: number,
  bio: string,
  change: string,
  created:[{nft_id: string}],
  owned:[{nft_id: string}],
}
